### ISSUE TITLE
Errors reported during concurrency: Unexpected end of stream

### ISSUE THREAD

**Issue by hezhiqiang** [JohnSully/KeyDB#148]
i have two keydb servers, use active replication, and use haproxy, errors reported during concurrency: Unexpected end of stream

`redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream. 
    at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:202) 
    at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:43) 
    at redis.clients.jedis.Protocol.process(Protocol.java:155) 
    at redis.clients.jedis.Protocol.read(Protocol.java:220) 
    at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:318) 
    at redis.clients.jedis.Connection.getOne(Connection.java:296) 
    at redis.clients.jedis.Jedis.zincrby(Jedis.java:1568)`

**Comment by JohnSully** [comment]
Hi @hezhiqiang 

This can happen if KeyDB decides to close a connection, or if the server crashes.  Do you still have the logs from KeyDB from when this occurred?

**Comment by JohnSully** [comment]
This actually looks like the INCR crash we fixed back in 5.3.2.

Closing unless new information (like the callstack) is provided.
