### ISSUE TITLE
Multi-Master - rdbcompression seg faults

### ISSUE THREAD

**Issue by jameswestover** [JohnSully/KeyDB#204]
When running keydb 6.0.8-rc1 configured as multi-master with 6 nodes and `rdbcompression` enabled, the child processes for executing a BGSAVE segfaults causing replication to fail. 

I am compiling from source and building this into an Alpine container, so I may have missed a dependency somewhere but I can't tell.

Disabling this feature causes everything to work as expected. 

**To Reproduce**
Setup 6 keydb processes in a full mesh, multi-master mode with `rdbcompression` enabled.

** Log Files **
Core Dump

```
/ # gdb /opt/keydb/keydb-server core.98
GNU gdb (GDB) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-alpine-linux-musl".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /opt/keydb/keydb-server...
[New LWP 98]

warning: Can't read pathname for load map: No error information.
Core was generated by `keydb-server /etc/keydb/keydb.conf'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  lzf_compress (in_data=in_data@entry=0x55c1904f42d4 <GlobalHidden::server+11892>, in_len=in_len@entry=40, out_data=out_data@entry=0x55c191cf3830, out_len=out_len@entry=36) at lzf_c.c:146
146	lzf_c.c: No such file or directory.
```

Key DB Logs repeat these messages:

```
15:20:S 18 Jun 2020 14:51:56.904 * Background saving started by pid 844
15:20:S 18 Jun 2020 14:51:57.000 # Background saving terminated by signal 11
15:20:S 18 Jun 2020 14:51:57.000 # Connection with replica 10.0.0.1:6379 lost.
15:20:S 18 Jun 2020 14:51:57.000 # SYNC failed. BGSAVE child returned an error
15:20:S 18 Jun 2020 14:51:57.907 * Replica 10.0.0.1:6379 asks for synchronization
15:20:S 18 Jun 2020 14:51:57.907 * Full resync requested by replica 10.0.0.1:6379
15:20:S 18 Jun 2020 14:51:57.907 * Starting BGSAVE for SYNC with target: disk
15:20:S 18 Jun 2020 14:51:57.907 * Background saving started by pid 845
15:20:S 18 Jun 2020 14:51:58.003 # Background saving terminated by signal 11
15:20:S 18 Jun 2020 14:51:58.003 # Connection with replica 10.0.0.1:6379 lost.
15:20:S 18 Jun 2020 14:51:58.003 # SYNC failed. BGSAVE child returned an error
```

Thanks for the help!

**Comment by JohnSully** [comment]
Super odd, this is the same lzf decoder used in Redis for many versions.  I'm investigating.

**Comment by JohnSully** [comment]
Any chance you could get me a stack trace at the time of the crash? It may be caused by an incorrect length.

**Comment by jameswestover** [comment]
Where would I get that data from? All I could find diagnostic wise was what i posted.

**Comment by JohnSully** [comment]
Hi @jameswestover 

I see you already caught the exception in GDB.  All that you'd need is to type 'bt' in GDB after it breaks on the exception.  It will print the callstack which would help immensely.

KeyDB also normally logs this in its log in the form of a crash report.

**Comment by christianEQ** [comment]
I've reproduced this bug in an Alpine container. Still looking into the cause/a fix, but here's the stack trace for reference.

```
#0  lzf_compress (in_data=in_data@entry=0x5573a0fe5b74 <GlobalHidden::server+12308>, in_len=in_len@entry=40, out_data=out_data@entry=0x7f5b6e412910, out_len=out_len@entry=36) at lzf_c.c:146
#1  0x00005573a0e4fcfb in rdbSaveLzfStringObject (rdb=0x7f5b7063e9a0, s=0x5573a0fe5b74 <GlobalHidden::server+12308> "9529a0636d61afa4ee2697214f227deff415fb5d", len=len@entry=40) at rdb.cpp:356
#2  0x00005573a0e50075 in rdbSaveLzfStringObject (len=40, s=0x5573a0fe5b74 <GlobalHidden::server+12308> "9529a0636d61afa4ee2697214f227deff415fb5d", rdb=0x7f5b7063e9a0) at rdb.cpp:427
#3  rdbSaveRawString (rdb=rdb@entry=0x7f5b7063e9a0, s=s@entry=0x5573a0fe5b74 <GlobalHidden::server+12308> "9529a0636d61afa4ee2697214f227deff415fb5d", len=len@entry=40) at rdb.cpp:427
#4  0x00005573a0e5190e in rdbSaveAuxField (rdb=rdb@entry=0x7f5b7063e9a0, key=key@entry=0x5573a0f7f315, keylen=7, val=0x5573a0fe5b74 <GlobalHidden::server+12308>, vallen=40) at rdb.cpp:1063
#5  0x00005573a0e51994 in rdbSaveAuxFieldStrStr (rdb=rdb@entry=0x7f5b7063e9a0, key=key@entry=0x5573a0f7f315 "repl-id", val=<optimized out>) at rdb.cpp:1071
#6  0x00005573a0e51ed6 in rdbSaveInfoAuxFields (rdb=rdb@entry=0x7f5b7063e9a0, rdbflags=rdbflags@entry=0, rsi=rsi@entry=0x7f5b7063fb60) at rdb.cpp:1173
#7  0x00005573a0e521fc in rdbSaveRio (rdb=rdb@entry=0x7f5b7063e9a0, error=error@entry=0x7f5b7063e99c, rdbflags=rdbflags@entry=0, rsi=rsi@entry=0x7f5b7063fb60) at rdb.cpp:1263
#8  0x00005573a0e52f8f in rdbSaveFile (filename=0x7f5b7024d170 "dump-30001.rdb", rsi=rsi@entry=0x7f5b7063fb60) at rdb.cpp:1418
#9  0x00005573a0e531cf in rdbSave (rsi=0x7f5b7063fb60) at rdb.cpp:1384
#10 0x00005573a0e53e60 in saveCommand (c=0x7f5b6e405700) at rdb.cpp:2779
#11 0x00005573a0e21f7c in call (c=0x7f5b6e405700, flags=15) at server.cpp:3577
#12 0x00005573a0e22a41 in processCommand (c=c@entry=0x7f5b6e405700, callFlags=callFlags@entry=15) at server.cpp:4016
#13 0x00005573a0e2f700 in processCommandAndResetClient (c=0x7f5b6e405700, flags=15) at networking.cpp:2211
#14 0x00005573a0e348b3 in processInputBuffer (callFlags=<optimized out>, c=<optimized out>) at networking.cpp:2272
#15 processInputBuffer (c=0x7f5b6e405700, callFlags=15) at networking.cpp:2226
#16 0x00005573a0e37183 in processClients () at networking.cpp:2376
#17 0x00005573a0e1a2b0 in beforeSleep (eventLoop=0x7f5b70228100) at server.cpp:2242
#18 0x00005573a0e16b15 in aeMain (eventLoop=0x7f5b70228100) at ae.cpp:874
#19 0x00005573a0e1d234 in workerThreadMain (parg=<optimized out>) at server.cpp:5485
```
